server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
    org.example: DEBUG
  appenders:
    - type: console

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: Raunak@321
  url: jdbc:mysql://host.docker.internal:3306/todo_app?autoReconnect=true&useSSL=false
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hbm2ddl.auto: update  # Automatically update database schema (use 'validate' in production)
    current_session_context_class: thread
